import Head from 'next/head'
import { useState } from 'react'

// Data
import pageData from '../PageData/PageData'
import { cardPunkData } from '../components/CardsContainer/CardData'

// Components
import { Header, CardContainer, MainCard } from '../components'

export default function Home() {
    const [selectedId, setSelectedId] = useState(0)
    const [punkDataList] = useState(cardPunkData)
    return (
        <div className="mainPage">
            <Head>
                <title>Next Js Project Crypto App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <Header headerData={pageData.header} />
            <MainCard selectedId={selectedId} punkDataList={punkDataList} />
            <CardContainer
                setSelectedId={setSelectedId}
                punkDataList={punkDataList}
            />
        </div>
    )
}
